# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sakai-vue

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://goats.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_082ecb39541642b2bf0a3a49939f76a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cc98ecc0bc5a4d469fca44470fb4200a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: goats.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_082ecb39541642b2bf0a3a49939f76a3 }}/sakai-vue:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sakai-vue'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2f56a675235e4789be08ce1ec233d6c9 }}
        images: 'goats.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_082ecb39541642b2bf0a3a49939f76a3 }}/sakai-vue:${{ github.sha }}'